---
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: 'inventory/hosts.yaml'
    group_file: 'inventory/groups.yaml'
    defaults_file: 'inventory/defaults.yaml'

core:
  num_workers: 12

logging:
  enabled: true
  level: DEBUG
  file: "logs/nornir.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - Module: %(module)s - Func(%(funcName)s) - %(message)s"
  loggers: ['nornir', 'src.actions', 'src.utils']